//
// Created by rodion on 10/8/20.
//

#ifndef COMPUTERSHOP_MEMORYMODEL_STORAGE_COMPONENTSSTORAGE_H_
#define COMPUTERSHOP_MEMORYMODEL_STORAGE_COMPONENTSSTORAGE_H_

class ComponentsStorage {
 public:

};

#endif //COMPUTERSHOP_MEMORYMODEL_STORAGE_COMPONENTSSTORAGE_H_
